version: 2.1

orbs:
  terraform: hashicorp/terraform@1.1.0

workflows:
  version: 2
  apply_infra:
    jobs:
      - terraform/validate:
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate

      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
          requires:
            - terraform/plan
