
version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
  plan_infra:
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
   apply_infra:           
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - terraform/plan
